### PR TITLE
GUI

### PR DESCRIPTION
**Pull request by Kotolegokot**
Test menus guys pls before I merge it into master

### CODE REVIEW

**Review by Kotolegokot — COMMENTED** [review]
Everything looks OK. That Kotik must be a cool guy

**Comment by Shirerpeton** [comment]
Amazing work! But I have found some minor bugs. First, I can't change resolution of window, though I think it may be related to my desktop environment. Second, i think it would be more convinient if application would toggles between fullscreen and windowed mode immediatly after pressing toggle button. And wasd control order is more familiar than wsad.

**Comment by Kotolegokot** [comment]
I just found out that resolution changing has no effect at master either. Have you tested all this under Windows or Linux with KDE?

**Comment by Shirerpeton** [comment]
I have tested this only under Linux with KDE. And in master resolution is changing how it supposed do (just tried).

**Comment by Kotolegokot** [comment]
OK, thx

**Comment by Kotolegokot** [comment]
I tried to fix that. Check it out now

**Review by Shirerpeton — APPROVED** [review]
All ok now. Excellent work!

**Pull request merged**
