### PR TITLE
New generator based on chunks

### PR DESCRIPTION
**Pull request by Kotolegokot**

### CODE REVIEW

**Comment by Kotolegokot** [comment]
There's a bug with NaNs. I have to fix it before merging.

**Comment by Kotolegokot** [comment]
That nasty NaN bug has been successfully fixed, yo

**Comment by Kotolegokot** [comment]
Ohuyenniy PR, spasibo

**Comment by Kotolegokot** [comment]
Thank to @pienilinnunrata, I've fixed some bugs, and everything must now finally be ready

**Review by pienilinnunrata — APPROVED** [review]
Keep up the good work!

**Pull request merged**
